# Default values for n8n.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 5

image:
  repository: n8nio/n8n
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.51.1"

# values for Redis helm chart
redis:
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      size: 1Gi
  replica:
    replicaCount: 3
    persistence:
      size: 1Gi

# values for N8N
n8n:
  encryptionKey: "TJw2uLC1uSy2qQpFSjsjbFK/e/wKM7cz"
  log_level: "debug"
  timezone: "America/Edmonton"
  webhookUrl: https://api.powerboot.io
  auth:
    enabled: true
    username: "sysadmin@powerboot.ca"
    password: "UnhVVXUzMk*L92Dn2eF^25XOF48w"
  data:
    prune:
      enabled: true
      # prune old executions data after X hours
      max_age: "72"

# values for PostgreSql helm chart
postgresql:
  enabled: true
  auth:
    host: { secretKeyRef: { name: hippo-pguser-hippo, key: host } }
    database: "n8n"
    username: "postgres"
    password: "eEhoT3BUYUVvdg=="
  persistence:
    size: 1Gi

imagePullSecrets: []
nameOverride: "api"
fullnameOverride: "api"

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  host: n8n.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
